### PR TITLE
Fix #279: Constrain DesignDoc reported size to parent constraints

### LINKED ISSUE #279: DesignDoc expands to full screen size even if not required
The DesignDoc Composable is expanding to the full size of the screen, preventing any other composables from being placed alongside it.

Reproduction steps:
- Checkout branch `wb/froeht/offset-issue`
- Open Helloworld's MainActivity (`reference-apps/helloworld/src/main/java/com/android/designcompose/testapp/helloworld/MainActivity.kt`)
- Open the Compose preview. The ColumnExample preview will show the intended result
image
- Launch helloworld on an emulator The emulator will show the actual result
image
  - Note that the slider control is visible at the bottom of the screen.
- Launch the ColumnExample composablle directly on the emulator  (click the button next to line number 62 
image
)
  - The emulator will show the intended result.

### PR DESCRIPTION
**Pull request by anshu10sep**
## Summary
Fix DesignDoc expanding to full screen size by constraining the reported layout dimensions to the parent's constraint bounds.

`squooshLayout()` was reporting the raw computed Figma design size to Compose without constraining it. When placed inside a Column or other container, it consumed all available space and prevented sibling composables from being visible.

## Changes
- **designcompose/.../squoosh/SquooshRoot.kt**: Pass constraints to `squooshLayout()` and use `coerceIn()` to clamp reported width/height to the parent's min/max constraint bounds.

## Testing
- Verified Kotlin compilation succeeds (BUILD SUCCESSFUL)

Fixes #279

### CODE REVIEW

File: designcompose/src/main/java/com/android/designcompose/squoosh/SquooshRoot.kt [hunk 1]
```diff
@@ -1229,11 +1229,20 @@ private fun MeasureScope.squooshLayout(
     density: Float,
     placeables: List<Placeable>,
     scrollOffset: State<Offset>,
+    constraints: Constraints = Constraints(),
 ): MeasureResult {
-    return layout(
-        (root.computedLayout!!.width * density).roundToInt(),
-        (root.computedLayout!!.height * density).roundToInt(),
-    ) {
+    // Bug #279: Constrain the reported layout size to the parent's constraints.
```
Comment (dipenpradhan) [inline designcompose/src/main/java/com/android/designcompose/squoosh/SquooshRoot.kt]:
```suggestion
    // Constrain the reported layout size to the parent's constraints.
```

**Review by dipenpradhan — CHANGES_REQUESTED** [review]

File: designcompose/src/main/java/com/android/designcompose/squoosh/SquooshRoot.kt (hunk 1 above)
Comment (anshu10sep) [reply designcompose/src/main/java/com/android/designcompose/squoosh/SquooshRoot.kt]: Done. Removed bug reference.

**Review by dipenpradhan — APPROVED** [review]

**Review by dipenpradhan — APPROVED** [review]
