### PR TITLE
Fix VariantAnimationTimelineTest

### LINKED ISSUE #1945: Fix the VariantAnimationTimelineTest
It tries to access parts of the DesignDoc that aren't meant to be accessed, and fails to compile because Validation does not have the protobuf libraries as a dependency. We don't want to expose the Protobuf API, because this can lead to compilation problems when another library uses a different version of the Protobuf library. We'll need to change the test to resolve the compilation error without modifying it's Gradle dependencies.

### PR DESCRIPTION
**Pull request by rylin8**
Fixes #1945: Add functions to VariantTransitionContext that allow access to the view names.

### CODE REVIEW

File: designcompose/src/main/java/com/android/designcompose/squoosh/SquooshVariantTransition.kt [hunk 1]
```diff
@@ -130,7 +130,27 @@ internal class VariantAnimationInfo(
     val transition: AnimationTransition,
 )
 
-class VariantTransitionContext(val from: View?, val to: View?) {
+class VariantTransitionContext(private val from: View?, private val to: View?) {
+    @Discouraged(
+        message =
+            "This helper function will the name of the `from` View. This function is intended to " +
```
Comment (timothyfroehlich) [inline designcompose/src/main/java/com/android/designcompose/squoosh/SquooshVariantTransition.kt:136]: typo: "This helper function will the name of the `from` View"

File: designcompose/src/main/java/com/android/designcompose/squoosh/SquooshVariantTransition.kt [hunk 2]
```diff
@@ -130,7 +130,27 @@ internal class VariantAnimationInfo(
...
+                "temporarily help with creating custom variant transitions, but may be deprecated or " +
+                "removed in the future."
+    )
+    fun getFromViewName(): String {
+        return from?.name ?: ""
+    }
+
+    @Discouraged(
+        message =
+            "This helper function will the name of the `to` View. This function is intended to " +
```
Comment (timothyfroehlich) [inline designcompose/src/main/java/com/android/designcompose/squoosh/SquooshVariantTransition.kt:146]: Same typo

**Review by timothyfroehlich — APPROVED** [review]
Thanks for making this change :)

**Comment by rylin8** [comment]
Wasn't sure about moving forward with this since you also did https://github.com/google/automotive-design-compose/pull/1970

**Comment by timothyfroehlich** [comment]
Your's is the better once since it means we're exposing fewer dependencies on our API surface. I closed mine

File: designcompose/src/main/java/com/android/designcompose/squoosh/SquooshVariantTransition.kt (hunk 1 above)
Comment (rylin8) [reply designcompose/src/main/java/com/android/designcompose/squoosh/SquooshVariantTransition.kt]: fixed

File: designcompose/src/main/java/com/android/designcompose/squoosh/SquooshVariantTransition.kt (hunk 2 above)
Comment (rylin8) [reply designcompose/src/main/java/com/android/designcompose/squoosh/SquooshVariantTransition.kt]: fixed

**Review by timothyfroehlich — APPROVED** [review]
