### PR TITLE
Closes #471: Fix live update not updating positional changes

### LINKED ISSUE #471: Live update does not update fixed positional changes
When a live update occurs where nodes change position within a non-autolayout parent frame, the parent frame is not included in the list of changed nodes, so the parent isn't recomposed. Since node positions are performed in a parent frame's layout() function, the node that moved doesn't update its position.

### PR DESCRIPTION
**Pull request by rylin8**
When computing layout and determining nodes that changed, include the parent of the node as well. For text nodes, recompute text layout when the text style changes.

### CODE REVIEW

**Review by iamralpht — APPROVED** [review]

File: crates/layout/src/layout.rs [hunk 1]
```diff
@@ -108,9 +108,10 @@ impl LayoutManager {
     fn update_layouts(&mut self, taffy: &Taffy) -> Vec<i32> {
         fn update_layout(
             layout_id: i32,
+            parent_layout_id: i32,
             manager: &mut LayoutManager,
             taffy: &Taffy,
-            changed: &mut Vec<i32>,
+            changed: &mut HashSet<i32>,
```
Comment (iamralpht) [inline crates/layout/src/layout.rs:114]: I'm guessing the Kotlin side doesn't care what order the invalidations are in, so it's OK to move from a Vec to a Set (and avoid duplicate parents...).

Comment (rylin8) [reply crates/layout/src/layout.rs:114]: Yea it doesn't -- it just notifies them all in one pass.
